security:
    basic:
        enabled: false
        
spring:
        datasource:
            url: jdbc:h2:mem:mydb
            username: sa
            password:
            driver-class-name: org.h2.Driver
            platform: h2
        h2:
            console:
                enabled: true
                path: /console